common:
  policy_class: ACT
  state_dim: 128
  action_dim: 128
  camera_names: ['left', 'right']

model:
  enc_layers: 4
  dec_layers: 7
  nheads: 8
  hidden_dim: 512
  kl_weight: 10
  dim_feedforward: 3200
  lr_backbone: 1e-5
  backbone: resnet18
  image_feature_strategy: ACT_linear
  use_language_conditioning: False

data:
  image_resolution_hw: [240, 320]
